name: pr-checks
on:
  push:
    branches-ignore:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1
      - name: Get changed files
        id: changes
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "all_files<<EOF" >> $GITHUB_OUTPUT
          gh pr diff $pr_number --name-only | xargs >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - name: List all changed files
        run: |
          for file in ${{ steps.changes.outputs.all_files }}; do
            echo "$file was changed"
          done
