name: pr-checks
on:
  push:
    branches-ignore:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changes
        run: |
          echo $GITHUB_REF
          PR_NUMBER=$(echo $GITHUB_REF | sed -e "s|refs/heads/||")
          echo $PR_NUMBER
          echo "all_files<<EOF" >> $GITHUB_OUTPUT
          gh pr diff $PR_NUMBER --name-only | xargs >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - name: List all changed files
        run: |
          for file in ${{ steps.changes.outputs.all_files }}; do
            echo "$file was changed"
          done
